version: '3.9'

services:
  kotlinapp:
    container_name: kalahaapp
    build: # this is the build context: .  
      context: .
      dockerfile: Dockerfile
    ports: # port exposed to the host machine
      - "8080:8080"

volumes: # volume creation
  pgdata: {}